# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-13 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20180513_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='editor',
        ),
        migrations.AddField(
            model_name='book',
            name='editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Editor'),
        ),
    ]
