# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-30 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20180427_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='admingenre',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Genre'),
        ),
        migrations.AlterField(
            model_name='usergenre',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Genre'),
        ),
    ]
