# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-18 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20180513_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookscore',
            name='title',
            field=models.CharField(default='No title', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Editor'),
        ),
    ]
