# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-18 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20180518_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='genre',
            unique_together=set([]),
        ),
    ]
